# Generated by Django 5.2.12 on 2026-04-17 01:07

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('api_key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.IntegerField()),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('flaky', 'Flaky')], default='passed', max_length=20)),
                ('summary', models.JSONField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('environment', models.JSONField(blank=True, null=True)),
                ('ci_info', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project')),
            ],
            options={
                'db_table': 'test_runs',
                'ordering': ['-run_number'],
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spec_id', models.CharField(blank=True, default='', max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('suite_title', models.CharField(blank=True, default='', max_length=500)),
                ('file_path', models.CharField(blank=True, default='', max_length=500)),
                ('line', models.IntegerField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, size=None)),
                ('project_name', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('flaky', 'Flaky'), ('skipped', 'Skipped')], max_length=20)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('error_details', models.JSONField(blank=True, null=True)),
                ('results', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.project')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.testrun')),
            ],
            options={
                'db_table': 'test_cases',
            },
        ),
        migrations.AddConstraint(
            model_name='testrun',
            constraint=models.UniqueConstraint(fields=('project', 'run_number'), name='unique_project_run_number'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['run'], name='test_cases_run_id_d4fcc6_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['project', 'spec_id'], name='test_cases_project_3e6d60_idx'),
        ),
        migrations.AddIndex(
            model_name='testcase',
            index=models.Index(fields=['status'], name='test_cases_status_ea5204_idx'),
        ),
    ]
